spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  destination:
    folder: ${SPRING_DESTINATION_FOLDER}
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      speech:
        api-key: ${SPRING_AI_OPENAI_SPEECH_API_KEY}
      base-url: ${SPRING_AI_OPENAI_BASE_URL}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
    show-sql: ${SPRING_JPA_SHOW_SQL}

aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}

security:
  jwt:
    private:
      key: ${SECURITY_JWT_PRIVATE_KEY}
    user:
      generator: ${SECURITY_JWT_USER_GENERATOR}

deepseek:
  api:
    key: ${DEEPSEEK_API_KEY}
    url: ${DEEPSEEK_API_URL}

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_API_URL}

feign:
  client:
    config:
      default:
        loggerLevel: ${FEIGN_CLIENT_CONFIG_DEFAULT_LOGGERLEVEL}

logging:
  level:
    com.ia.alexander.client.ia: ${LOGGING_LEVEL_COM_IA_ALEXANDER_CLIENT_IA}
    feign: ${LOGGING_LEVEL_FEIGN}

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_API_URL}
